wandb_version: 1

config:
  desc: null
  value: ./config.json
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686617250.673667
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.8.5
      5: 0.15.4
      8:
      - 5
