# set dir or path
image_dir: "/opt/ml/input/data/train/DCM"
label_dir: "/opt/ml/input/data/train/outputs_json"
test_image_dir: "/opt/ml/input/data/test/DCM"

save_model_dir: "/opt/ml/input/results/baseline_efficient_unet"
save_model_fname: "efficient_unet_best_model.pt"

save_submit_dir: "/opt/ml/input/results/baseline_efficient_unet"
save_submit_fname: "efficient_unet_best_model.csv"

# set model
model: "Unet" # Unet Unet++ MAnet Linknet FPN PSPNet PAN DeepLabV3 DeepLabV3+
encoder_name: "efficientnet-b0"
encoder_weights: "imagenet"

# hyperparameter
seed: 42
epochs: 100
batch_size: 16
num_workers: 4
learning_rate: 0.0001   # 1e-4
weight_decay: 0.000001  # 1e-6
optimizer: "Adam"

# set log
log_step: 20
val_every: 5