MODEL:
  BACKBONE: 
    TYPE: 'swin' # 'resnet' or 'swin'
  PRETRAINED_WEIGHTS: 
  IS_TRAINING: True    
  RESNETS:
    DEPTH: 50
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False    
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  SWIN:
    TYPE: "base" # "tiny" or "small" or "base" or "large"
    EMBED_DIM: 96
    DEPTHS: [2 2 6 2]
    NUM_HEADS: [3 6 12 24]
    PATCH_SIZE: 4
    WINDOW_SIZE: 7
    MLP_RATIO: 4.
    QKV_BIAS: True
    QK_SCALE: 
    DROP_RATE: 0.
    ATTN_DROP_RATE: 0.
    DROP_PATH_RATE: 0.3
    APE: False
    PATCH_NORM: True
    OUT_INDICES: (0 1 2 3)
    PRETRAIN_IMG_SIZE: 384
    USE_CHECKPOINT: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    
  META_ARCHITECTURE: "MaskFormer"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 29
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    BOUNDARY_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 29
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: True
      PANOPTIC_ON: True
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
